# -*- coding: utf-8 -*-
"""[NEDO-4]IBM(量子自動分割版) v3.4-005

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11aazjXsgTyhVJ7v0wVZZqzeyd4nMKyls
"""

# -*- coding: utf-8 -*-
"""[NEDO-4]IBM(量子版) v3.0-002

変更点 (v3.0-001 → v3.0-002):
  【高速化】QAOA クラスタ分割対応
    - PHASE 1 QAOA: 全N変数を一括処理 → n_clusters 個のサブ問題に分割して解く
    - PHASE 2 QAOA: 同様にサブ問題分割を適用
    - サブ問題サイズ N_sub = ceil(N / n_clusters) を自動計算
    - 各クラスタの結果(best_alloc)を統合して全体インセンティブを算出
    - 指数コスト O(2^N) → O(n_clusters × 2^(N/n_clusters)) に大幅削減

    例) N=30, n_clusters=3 の場合
      分割前: 2^30 ≈ 10億 状態
      分割後: 3 × 2^10 ≈ 3,072 状態  → 約33万倍の高速化
"""

import subprocess, sys, os
os.system("rm -rf ~/.cache/matplotlib")
os.system("apt-get -y install fonts-noto-cjk > /dev/null 2>&1")

import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'Noto Sans CJK JP'
plt.rcParams['font.sans-serif'] = ['Noto Sans CJK JP']
plt.rcParams['axes.unicode_minus'] = False
print('✅ 日本語フォント設定完了！')

# ============================================================
# 1. パッケージインストール
# ============================================================
pkgs = ["ortools", "pyproj", "pandas", "plotly", "matplotlib",
        "qiskit", "qiskit-aer", "qiskit-ibm-runtime",
        "qiskit-algorithms", "qiskit-optimization", "scikit-learn"]
for pkg in pkgs:
    subprocess.run(
        [sys.executable, "-m", "pip", "install", "--upgrade", pkg, "-q"],
        stdout=subprocess.DEVNULL,
    )
print("✅ パッケージインストール完了")

# ============================================================
# 2. IBM Quantum 認証
# ============================================================
from qiskit_ibm_runtime import QiskitRuntimeService
import getpass

print("=== IBM Quantum ログイン ===")
ibm_service = None
try:
    token = getpass.getpass("IBM Quantum API Token を入力してください (スキップ可): ")
    if token.strip():
        QiskitRuntimeService.save_account(
            channel="ibm_quantum_platform",
            token=token,
            overwrite=True,
        )
        ibm_service = QiskitRuntimeService()
        print("✅ IBM Quantum に接続しました！")
    else:
        print("⚠️ トークン未入力 → AerSimulator を使用")
except Exception as e:
    print(f"⚠️ 認証エラー: {e} → AerSimulator を使用")

# ============================================================
# 3. インポート
# ============================================================
import math
import pandas as pd
import numpy as np
import pyproj
import random
import plotly.graph_objs as go
import plotly.express as px
from datetime import datetime
from IPython.display import display

from ortools.constraint_solver import pywrapcp, routing_enums_pb2
from sklearn.cluster import KMeans

from qiskit import QuantumCircuit, transpile
from qiskit_aer import AerSimulator

# インポート元は qiskit_optimization.minimum_eigensolvers を使用
# （qiskit_algorithms.QAOA は AerSampler(SamplerV2) と非互換のため）
from qiskit_aer.primitives import SamplerV2 as AerSampler
from qiskit_optimization import QuadraticProgram
from qiskit_optimization.algorithms import MinimumEigenOptimizer
from qiskit_optimization.optimizers import COBYLA
from qiskit_optimization.minimum_eigensolvers import QAOA

print("✅ 全インポート完了")

# ============================================================
# 4. n_nodesに応じた最適設定関数
# ============================================================
def get_experiment_config(n_nodes):
    if n_nodes < 20:
        return {
            "use_cluster":   False,
            "qaoa_method":   "statevector",
            "qaoa_shots":    2048,
            "qaoa_maxiter":  150,
            "qaoa_reps":     1,
            "vrp_time_limit": 120,
            "vrp_clusters":  2,           # NameError防止: 常に定義
        }
    else:
        return {
            "use_cluster":   True,
            "qaoa_method":   "statevector",
            "qaoa_shots":    1024,
            "qaoa_maxiter":  100,
            "qaoa_reps":     1,
            "vrp_clusters":  2 if n_nodes <= 35 else 3,
            "vrp_time_limit": 180 if n_nodes <= 30 else 300,
            "vrp_capacity":  [350, 350] if n_nodes <= 35 else [400, 400]
        }

# ============================================================
# 5. データ準備
# ============================================================
try:
    from google.colab import files
    print("CSVファイルをアップロードしてください（map_Tokyo-city1.csv など）")
    uploaded = files.upload()
    filename = list(uploaded.keys())[0]
    df = pd.read_csv(filename)
    print(f"✅ アップロード完了: {filename} ({len(df)} 拠点)")
except Exception:
    print("Warning: CSV が見つからないためダミーデータを使用します。")
    data = {
        'source_name': [f'Location_{i}' for i in range(11)],
        'lon':         np.linspace(139.700, 139.710, 11),
        'lat':         np.linspace(35.680,  35.690,  11),
        'risk_score':  np.random.randint(10, 100, 11),
    }
    df = pd.DataFrame(data)
    filename = "dummy_data.csv"

df = df.reset_index(drop=True)
display(df.head())

n_nodes    = len(df)
n_vehicles = 2
depot      = 0
geod       = pyproj.Geod(ellps="WGS84")
farmers    = df["source_name"].tolist()

# ============================================================
# 時間計測の準備
# ============================================================
overall_start_time = datetime.now()
print(f"【全プロセス開始】 {overall_start_time.strftime('%Y-%m-%d %H:%M:%S')}\n")

# ============================================================
# 設定適用
# ============================================================
config     = get_experiment_config(n_nodes)
n_clusters = config["vrp_clusters"]
print(f"✅ n_nodes = {n_nodes} | クラスタ分割: {config['use_cluster']} | クラスタ数: {n_clusters}")

# ------------------------------------------------------------------
# ★★★ QAOA用サブ問題サイズを自動計算 ★★★
#
#   N_sub = ceil(N / n_clusters)
#   例) N=30, n_clusters=3 → N_sub=10
#       N=11, n_clusters=2 → N_sub=6
#
#   状態空間: 2^N → n_clusters × 2^N_sub（指数削減）
# ------------------------------------------------------------------
N_sub = math.ceil(n_nodes / n_clusters)
print(f"✅ QAOAサブ問題サイズ N_sub = {N_sub}  (= ceil({n_nodes}/{n_clusters}))")
print(f"   状態空間削減: 2^{n_nodes} → {n_clusters}×2^{N_sub}  "
      f"({2**n_nodes:,} → {n_clusters * 2**N_sub:,} 状態)")

all_routes = []

# ============================================================
# PHASE 1 ① VRP（KMeansクラスタ共通 → 条件分岐で容量制約を変える）
# ============================================================
print("\n▶ OR-Tools による配送ルート最適化中...")
print(f"【① VRP最適化開始】 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
vrp_p1_start = datetime.now()
geod = pyproj.Geod(ellps="WGS84")

# KMeansクラスタリング（n<20 / n>=20 共通）
coords     = df[['lat', 'lon']].values
kmeans     = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
df['cluster'] = kmeans.fit_predict(coords)
print(f"  → {n_nodes}拠点を {n_clusters}クラスタに分割")

if not config["use_cluster"]:
    # ==================== n < 20: 容量固定VRP ====================
    print(f"  → 容量固定VRP (n={n_nodes})")
    base_cap = 310

    for cl_id in range(n_clusters):
        cluster_df   = df[df['cluster'] == cl_id].reset_index(drop=False)
        cluster_size = len(cluster_df)
        if cluster_size < 3:
            print(f"  クラスタ {cl_id}: {cluster_size}拠点 → スキップ")
            continue
        print(f"  クラスタ {cl_id}: {cluster_size}拠点でVRP実行中...")

        manager = pywrapcp.RoutingIndexManager(cluster_size, n_vehicles, 0)
        routing = pywrapcp.RoutingModel(manager)

        def distance_callback(from_index, to_index):
            i = manager.IndexToNode(from_index)
            j = manager.IndexToNode(to_index)
            _, _, dist = geod.inv(
                cluster_df.loc[i, "lon"], cluster_df.loc[i, "lat"],
                cluster_df.loc[j, "lon"], cluster_df.loc[j, "lat"])
            return max(1, int(dist))

        transit_idx = routing.RegisterTransitCallback(distance_callback)
        routing.SetArcCostEvaluatorOfAllVehicles(transit_idx)

        def demand_callback(index):
            node = manager.IndexToNode(index)
            return 0 if node == 0 else int(cluster_df.loc[node, "risk_score"])

        demand_idx = routing.RegisterUnaryTransitCallback(demand_callback)
        routing.AddDimensionWithVehicleCapacity(
            demand_idx, 0, [base_cap, base_cap], True, "Capacity")

        search_params = pywrapcp.DefaultRoutingSearchParameters()
        search_params.time_limit.seconds = config["vrp_time_limit"]
        search_params.first_solution_strategy = (
            routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)
        search_params.local_search_metaheuristic = (
            routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH)
        solution = routing.SolveWithParameters(search_params)

        if solution:
            print(f"    → クラスタ {cl_id} で解を発見")
            for vehicle_id in range(n_vehicles):
                index      = routing.Start(vehicle_id)
                route_list = []
                while not routing.IsEnd(index):
                    node_idx       = manager.IndexToNode(index)
                    original_index = cluster_df.loc[node_idx, 'index']
                    route_list.append({
                        'original_index': original_index,
                        'cluster': cl_id, 'vehicle_id': vehicle_id,
                        'node_in_cluster': node_idx})
                    index = solution.Value(routing.NextVar(index))
                if len(route_list) > 1:
                    all_routes.extend(route_list)
        else:
            print(f"    ⚠️ クラスタ {cl_id} で解が見つかりませんでした")

else:
    # ==================== n >= 20: 容量緩和VRP ====================
    print(f"  → 容量緩和VRP (クラスタ数={n_clusters})")
    base_capacity = config["vrp_capacity"][0]

    for cl_id in range(n_clusters):
        cluster_df   = df[df['cluster'] == cl_id].reset_index(drop=False)
        cluster_size = len(cluster_df)
        if cluster_size < 3:
            print(f"  クラスタ {cl_id}: {cluster_size}拠点 → スキップ")
            continue
        print(f"  クラスタ {cl_id}: {cluster_size}拠点でVRP実行中...")

        cluster_total      = cluster_df["risk_score"].sum()
        vehicle_capacities = [max(base_capacity, int(cluster_total * 0.6) + 50)] * 2

        manager = pywrapcp.RoutingIndexManager(cluster_size, 2, 0)
        routing = pywrapcp.RoutingModel(manager)

        def distance_callback(from_index, to_index):
            i = manager.IndexToNode(from_index)
            j = manager.IndexToNode(to_index)
            _, _, dist = geod.inv(
                cluster_df.loc[i, "lon"], cluster_df.loc[i, "lat"],
                cluster_df.loc[j, "lon"], cluster_df.loc[j, "lat"])
            return max(1, int(dist))

        transit_idx = routing.RegisterTransitCallback(distance_callback)
        routing.SetArcCostEvaluatorOfAllVehicles(transit_idx)

        def demand_callback(index):
            node = manager.IndexToNode(index)
            return 0 if node == 0 else int(cluster_df.loc[node, "risk_score"])

        demand_idx = routing.RegisterUnaryTransitCallback(demand_callback)
        routing.AddDimensionWithVehicleCapacity(
            demand_idx, 0, vehicle_capacities, True, "Capacity")

        search_params = pywrapcp.DefaultRoutingSearchParameters()
        search_params.time_limit.seconds = config["vrp_time_limit"]
        search_params.first_solution_strategy = (
            routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)
        search_params.local_search_metaheuristic = (
            routing_enums_pb2.LocalSearchMetaheuristic.GUIDED_LOCAL_SEARCH)
        solution = routing.SolveWithParameters(search_params)

        if solution:
            print(f"    → クラスタ {cl_id} で解を発見")
            for vehicle_id in range(2):
                index      = routing.Start(vehicle_id)
                route_list = []
                while not routing.IsEnd(index):
                    node_idx       = manager.IndexToNode(index)
                    original_index = cluster_df.loc[node_idx, 'index']
                    route_list.append({
                        'original_index': original_index,
                        'cluster': cl_id, 'vehicle_id': vehicle_id,
                        'node_in_cluster': node_idx})
                    index = solution.Value(routing.NextVar(index))
                if len(route_list) > 1:
                    all_routes.extend(route_list)
        else:
            print(f"    ⚠️ クラスタ {cl_id} で解が見つかりませんでした")

# ====================== VRP結果統合 ======================
if all_routes:
    result_table = pd.DataFrame(all_routes)
    result_table = result_table.merge(
        df, left_on='original_index', right_index=True, how='left')
    result_table = result_table.rename(columns={'original_index': '地点'})
    result_table["到着順"] = result_table.groupby("vehicle_id").cumcount()
    result_table["累積距離"] = 0

    for vehicle_id in result_table["vehicle_id"].unique():
        mask     = result_table["vehicle_id"] == vehicle_id
        sub      = result_table[mask].copy().sort_values("到着順")
        cum_dist = 0
        prev_lon = prev_lat = None
        for idx, row in sub.iterrows():
            if prev_lon is not None:
                _, _, dist = geod.inv(prev_lon, prev_lat, row["lon"], row["lat"])
                cum_dist  += int(dist)
            result_table.loc[idx, "累積距離"] = cum_dist
            prev_lon, prev_lat = row["lon"], row["lat"]

    route_v0 = result_table.query("vehicle_id == 0").copy()
    route_v1 = result_table.query("vehicle_id == 1").copy()
    print(f"  → 全クラスタ統合完了: {len(result_table)} 拠点")
else:
    print("  ⚠️ すべてのクラスタで解が見つかりませんでした → フォールバック")
    route_v0             = df.copy()
    route_v0["vehicle_id"] = 0
    route_v0["到着順"]   = range(len(route_v0))
    route_v0["累積距離"] = 0
    route_v1 = pd.DataFrame()

# デポを先頭・末尾に追加
for route in [route_v0, route_v1]:
    if not route.empty:
        first = route.iloc[[0]].copy()
        route = pd.concat([first, route, first], ignore_index=True)

# 巡回ルート詳細出力
print("\n===== 車両1 巡回ルート（累積距離詳細） =====")
print(route_v0[["到着順", "地点", "source_name", "risk_score", "累積距離"]].to_string(index=False))
print("\n===== 車両2 巡回ルート（累積距離詳細） =====")
if not route_v1.empty:
    print(route_v1[["到着順", "地点", "source_name", "risk_score", "累積距離"]].to_string(index=False))
else:
    print("  （車両2 のルートなし）")

# Plotly Mapbox
traces = []
for route, color, name in zip([route_v0, route_v1], ["red", "blue"], ["車両1", "車両2"]):
    if route.empty:
        continue
    traces.append(go.Scattermapbox(
        lon=route["lon"], lat=route["lat"],
        mode="markers+text+lines",
        text=(route["source_name"].astype(str)
              + "<br>到着順: " + route["到着順"].astype(str)
              + "<br>risk_score: " + route["risk_score"].astype(str)
              + "<br>累積: " + route["累積距離"].astype(str) + "m"),
        marker=dict(size=route["risk_score"] / 10),
        line=dict(color=color, width=3),
        name=name,
    ))
fig_route = go.Figure(data=traces)
fig_route.update_layout(
    mapbox_style="open-street-map",
    mapbox=dict(center=dict(lat=35.6896, lon=139.7006), zoom=12),
    title="【PHASE 1】最適配送ルート（クラスタ分割方式）",
    height=700,
)
fig_route.show()

print("\n===== 車両1 巡回ルート（累積距離詳細） =====")
rv0 = route_v0.copy()
rv0["累積距離(km)"] = (rv0["累積距離"] / 1000).round(2)
display(rv0[["到着順", "source_name", "risk_score", "累積距離(km)"]].sort_values("到着順"))
print("\n===== 車両2 巡回ルート（累積距離詳細） =====")
if not route_v1.empty:
    rv1 = route_v1.copy()
    rv1["累積距離(km)"] = (rv1["累積距離"] / 1000).round(2)
    display(rv1[["到着順", "source_name", "risk_score", "累積距離(km)"]].sort_values("到着順"))
else:
    print("  （車両2 のルートなし）")

vrp_end_time = datetime.now()
vrp_time     = (vrp_end_time - vrp_p1_start).total_seconds()
print(f"\n【①  VRP（配送ルート最適化完了-実行Time】 {vrp_end_time.strftime('%Y-%m-%d %H:%M:%S')}")


# ==============================================================
# ★★★ QAOA共通ヘルパー関数（クラスタ分割対応） ★★★
#
#  処理フロー:
#    1. scores_list を n_cl 個のサブリストに均等分割
#       インデックス [0..N_sub), [N_sub..2*N_sub), ...
#    2. 各サブ問題を QAOA で独立に解く
#       サブ問題サイズ ≤ ceil(N/n_cl)
#    3. 全サブ問題の選択マスクを元のインデックスに戻して結合
#    4. 統合された selected_mask (長さ N, int) を返す
#
#  状態空間:  O(2^N)  →  O(n_cl × 2^ceil(N/n_cl))
# ==============================================================
def solve_qaoa_clustered(scores_list, label_prefix, qaoa_config, n_cl):
    """
    scores_list  : 各拠点のスコア (list, 長さ N)
    label_prefix : 変数名プレフィックス（"x" or "y"）
    qaoa_config  : get_experiment_config() の戻り値 dict
    n_cl         : QAOAクラスタ分割数

    戻り値       : selected_mask (np.ndarray[int], 長さ N)
    """
    N        = len(scores_list)
    N_sub_cl = math.ceil(N / n_cl)
    print(f"  [QAOA分割] N={N} → {n_cl}サブ問題 × 最大N_sub={N_sub_cl}")
    print(f"  [QAOA分割] 状態空間: 2^{N}={2**N:,} → "
          f"{n_cl}×2^{N_sub_cl}={n_cl * 2**N_sub_cl:,}")

    # AerSampler（サブ問題共通）
    sampler = AerSampler(
        options={
            "backend_options": {
                "method":               qaoa_config["qaoa_method"],
                "precision":            "single",
                "max_parallel_threads": 0,
            },
            "run_options": {"shots": qaoa_config["qaoa_shots"]},
        }
    )

    full_mask = np.zeros(N, dtype=int)

    for cl_id in range(n_cl):
        start      = cl_id * N_sub_cl
        end        = min(start + N_sub_cl, N)
        sub_scores = scores_list[start:end]
        sub_size   = len(sub_scores)
        sub_max_sel = max(1, sub_size // 2)

        print(f"    サブ問題 {cl_id}: インデックス [{start}:{end}] "
              f"({sub_size}変数, 上限選択数={sub_max_sel})")

        # QuadraticProgram 構築
        qp = QuadraticProgram(name=f"Sub_{label_prefix}_{cl_id}")
        for i in range(sub_size):
            qp.binary_var(name=f"{label_prefix}_{i}")
        qp.minimize(
            linear={f"{label_prefix}_{i}": -sub_scores[i]
                    for i in range(sub_size)})
        qp.linear_constraint(
            linear={f"{label_prefix}_{i}": 1 for i in range(sub_size)},
            sense="<=",
            rhs=sub_max_sel,
            name=f"budget_{cl_id}",
        )

        # QAOA ソルバー
        solver    = QAOA(
            sampler=sampler,
            optimizer=COBYLA(maxiter=qaoa_config["qaoa_maxiter"]),
            reps=qaoa_config["qaoa_reps"],
        )
        optimizer = MinimumEigenOptimizer(solver)

        try:
            result               = optimizer.solve(qp)
            sub_mask             = np.array(result.x, dtype=int)
            full_mask[start:end] = sub_mask
            print(f"      → 完了: {sub_mask.sum()}/{sub_size} 拠点選択")
        except Exception as e:
            print(f"      ⚠️ サブ問題 {cl_id} 失敗: {e} → スコア上位で代替")
            top_idx  = np.argsort(sub_scores)[-sub_max_sel:]
            sub_mask = np.zeros(sub_size, dtype=int)
            sub_mask[top_idx] = 1
            full_mask[start:end] = sub_mask

    return full_mask


# ==============================================================
# PHASE 1 ② インセンティブ配分最適化 ─ QAOA（クラスタ分割版）
# ==============================================================
print("\n▶ QAOA によるインセンティブ選択最適化中 (PHASE 1) [クラスタ分割版]...")
print(f"\n【②  インセンティブ配分最適化開始-実行Time】 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
qaoa_p1_start = datetime.now()

economic_impacts = df["risk_score"].tolist()
ghg_reductions   = economic_impacts
budget_p1        = 1000.0
max_select       = max(1, n_nodes // 2)

# LP文字列確認用（全体版 QuadraticProgram）
qp_p1_full = QuadraticProgram(name="IncentiveP1_Full")
for i in range(n_nodes):
    qp_p1_full.binary_var(name=f"x_{i}")
qp_p1_full.minimize(
    linear={f"x_{i}": -(ghg_reductions[i] + economic_impacts[i])
            for i in range(n_nodes)})
qp_p1_full.linear_constraint(
    linear={f"x_{i}": 1 for i in range(n_nodes)},
    sense="<=", rhs=max_select, name="budget_limit")
print(f"  QuadraticProgram (P1 全体参照): {n_nodes} 変数, 上限選択数={max_select}")
print(qp_p1_full.export_as_lp_string())

# ★ QAOA クラスタ分割実行
scores_p1        = [ghg_reductions[i] + economic_impacts[i] for i in range(n_nodes)]
selected_mask_p1 = solve_qaoa_clustered(
    scores_list=scores_p1, label_prefix="x",
    qaoa_config=config, n_cl=n_clusters)
n_selected_p1 = selected_mask_p1.sum()
print(f"  P1 全体選択拠点数: {n_selected_p1} / {n_nodes}")

# インセンティブ配分計算
SELECTED_RATIO  = 0.70
remaining_ratio = 1.0 - SELECTED_RATIO

best_alloc_p1 = np.zeros(n_nodes)
scores_p1_arr = np.array(scores_p1, dtype=float)

if n_selected_p1 > 0:
    sel_scores = scores_p1_arr * selected_mask_p1
    sel_total  = sel_scores.sum()
    if sel_total > 0:
        best_alloc_p1 += (sel_scores / sel_total) * (budget_p1 * SELECTED_RATIO)

non_mask = 1 - selected_mask_p1
n_non    = non_mask.sum()
if n_non > 0:
    best_alloc_p1 += non_mask * (budget_p1 * remaining_ratio / n_non)
else:
    best_alloc_p1 = (scores_p1_arr / scores_p1_arr.sum()) * budget_p1

def energy_p1_score(incentives, ghg_red, econ_imp, fairness_weight=0.5):
    total_ghg    = sum(i * g for i, g in zip(incentives, ghg_red))
    total_econ   = sum(i * e for i, e in zip(incentives, econ_imp))
    fairness_pen = fairness_weight * (max(incentives) - min(incentives))
    return (total_ghg + total_econ) - fairness_pen

max_score_p1 = energy_p1_score(best_alloc_p1.tolist(), ghg_reductions, economic_impacts)

print("\n最適インセンティブ配分（PHASE 1 - QAOA クラスタ分割版）:")
for f, alloc in zip(farmers, best_alloc_p1):
    print(f"  {f}: ¥{alloc:.2f}")
print(f"最大スコア: {max_score_p1:.2f}")

qaoa_p1_end  = datetime.now()
qaoa_p1_time = (qaoa_p1_end - qaoa_p1_start).total_seconds()
print(f"  QAOA P1 実行時間: {qaoa_p1_time:.2f} 秒")
print(f"\n【②  インセンティブ配分最適化完了-実行Time】 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

# matplotlib 棒グラフ
plt.figure(figsize=(12, 5))
bars = plt.bar(farmers, best_alloc_p1, color="mediumseagreen")
plt.title("【PHASE 1】Incentive allocation (QAOA クラスタ分割版)")
plt.ylabel("Allocation amount (JPY)")
plt.xticks(rotation=45, ha="right")
for bar in bars:
    h = bar.get_height()
    plt.text(bar.get_x() + bar.get_width() / 2, h + 5,
             f"¥{h:.0f}", ha="center", va="bottom")
plt.tight_layout()
plt.show()


# ============================================================
# ============================================================
# PHASE 2: 量子強化 + 衛星連動最適化
# ============================================================
# ============================================================
print("\n" + "=" * 70)
print("  PHASE 2: 量子強化 衛星連動型最適化")
print("=" * 70)

# ----------------------------------------------------------
# PHASE 2 ③  衛星リスク予測クラス
# ----------------------------------------------------------
class SatelliteRiskPredictor:
    """衛星メトリクス（S1 SAR / GPM）から長期リスクを予測するクラス"""
    def __init__(self, locations_df):
        self.locations = locations_df

    def fetch_satellite_metrics(self):
        metrics = []
        for _ in self.locations.iterrows():
            s1  = random.uniform(-15, 5)
            gpm = random.uniform(0.8,  1.5)
            metrics.append({"s1": s1, "gpm": gpm})
        return metrics

    def predict_long_term_risk(self):
        metrics = self.fetch_satellite_metrics()
        risks   = []
        for m in metrics:
            base = abs(m["s1"]) * 2.0 + m["gpm"] * 40.0
            risks.append(round(min(100, max(0, base)), 1))
        return risks

# ----------------------------------------------------------
# PHASE 2 ③  量子リスク予測関数
# ----------------------------------------------------------
def quantum_risk_predictor(df_in, shots=1024):
    """量子回路（H gate）のサンプリング確率を衛星リスク計算に組み込む"""
    backend = AerSimulator()
    risks   = []
    for _ in range(len(df_in)):
        qc = QuantumCircuit(1)
        qc.h(0)
        qc.measure_all()
        transpiled = transpile(qc, backend)
        job        = backend.run(transpiled, shots=shots)
        counts     = job.result().get_counts()
        prob1      = counts.get('1', 0) / shots
        s1         = random.uniform(-15, 5) * (prob1 * 2 - 1)
        gpm        = random.uniform(0.8,  1.5)
        risk       = min(100, max(0, abs(s1) * 2.0 + gpm * 40))
        risks.append(round(risk, 1))
    return risks

print("▶ 量子乱数 + 衛星データによる将来リスク予測...")
df["risk_score_static"] = df["risk_score"].copy()
df["risk_score"]        = quantum_risk_predictor(df)
display(df[["source_name", "risk_score_static", "risk_score"]])

# ----------------------------------------------------------
# PHASE 2 ④  量子 QKD 鍵生成
# ----------------------------------------------------------
def quantum_qkd_key(n_bits=16):
    """Bell 回路で量子もつれ測定し QKD 鍵文字列を生成する"""
    qc = QuantumCircuit(2, 2)
    qc.h(0)
    qc.cx(0, 1)
    qc.measure([0, 1], [0, 1])
    backend    = AerSimulator()
    transpiled = transpile(qc, backend)
    job        = backend.run(transpiled, shots=1)
    result     = job.result().get_counts()
    key        = list(result.keys())[0]
    return f"QKD-KEY-{int(key, 2):0{n_bits}b}"

print(f"[QKD] 生成された量子鍵: {quantum_qkd_key()}")

# ----------------------------------------------------------
# PHASE 2 ⑤  VRP（動的リスク考慮） ─ OR-Tools 1 車両
# ----------------------------------------------------------
def solve_routing_p2(df_in):
    """動的リスクスコアを反映した 1 台 VRP を解き巡回距離を返す"""
    print(f"\n【⑤  VRP（動的リスク考慮開始-実行Time】 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    vrp_p2_start = datetime.now()

    manager_p2 = pywrapcp.RoutingIndexManager(len(df_in), 1, 0)
    routing_p2 = pywrapcp.RoutingModel(manager_p2)
    geod_p2    = pyproj.Geod(ellps="WGS84")

    def dist_cb(i, j):
        ni = manager_p2.IndexToNode(i)
        nj = manager_p2.IndexToNode(j)
        _, _, d = geod_p2.inv(
            df_in["lon"].iloc[ni], df_in["lat"].iloc[ni],
            df_in["lon"].iloc[nj], df_in["lat"].iloc[nj])
        return int(d)

    routing_p2.SetArcCostEvaluatorOfAllVehicles(
        routing_p2.RegisterTransitCallback(dist_cb))
    params = pywrapcp.DefaultRoutingSearchParameters()
    params.first_solution_strategy = (
        routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)
    sol = routing_p2.SolveWithParameters(params)

    vrp_p2_end  = datetime.now()
    vrp_p2_time = (vrp_p2_end - vrp_p2_start).total_seconds()
    print(f"\n【⑤  VRP（動的リスク考慮完了-実行Time】 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    return (sol.ObjectiveValue(), vrp_p2_time) if sol else (999999, 0)

base_dist_p2, vrp_p2_time = solve_routing_p2(df)
print(f"将来リスク考慮後の巡回距離: {base_dist_p2} m")

# ----------------------------------------------------------
# PHASE 2 ⑥  統合インセンティブ最適化 ─ QAOA（クラスタ分割版）
# ----------------------------------------------------------
print("\n▶ QAOA によるリスク連動インセンティブ最適化中 (PHASE 2) [クラスタ分割版]...")
print(f"\n【⑥  QAOA によるリスク連動開始-実行Time】 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
qaoa_p2_start = datetime.now()

# QKD 由来の量子乱数シードを設定
random.seed(int.from_bytes(quantum_qkd_key(8).encode(), 'big') % (2 ** 32))

# PHASE 2 重みパラメータ
W_IMPACT      = 8.0
W_ECON        = 1.0
W_FAIRNESS    = 0.1
BUDGET_P2     = 1000.0
max_select_p2 = max(1, (n_nodes // 2) + 1)

# 各拠点の線形スコア
econ_scale_p2    = 1000.0 / base_dist_p2 if base_dist_p2 > 0 else 0.001
risk_scores_p2   = df["risk_score"].tolist()
linear_scores_p2 = [
    W_IMPACT * risk_scores_p2[i] + W_ECON * econ_scale_p2
    for i in range(n_nodes)
]

# LP文字列確認用（全体版）
qp_p2_full = QuadraticProgram(name="IncentiveP2_Full")
for i in range(n_nodes):
    qp_p2_full.binary_var(name=f"y_{i}")
qp_p2_full.minimize(
    linear={f"y_{i}": -linear_scores_p2[i] for i in range(n_nodes)})
qp_p2_full.linear_constraint(
    linear={f"y_{i}": 1 for i in range(n_nodes)},
    sense="<=", rhs=max_select_p2, name="budget_limit_p2")
print(f"  QuadraticProgram (P2 全体参照): {n_nodes} 変数, 上限選択数={max_select_p2}")
print(qp_p2_full.export_as_lp_string())

# ★ QAOA クラスタ分割実行（P2 は reps=2, maxiter=120）
config_p2 = dict(config)
config_p2["qaoa_reps"]    = 2
config_p2["qaoa_maxiter"] = 120
config_p2["qaoa_shots"]   = 1024
config_p2["qaoa_method"]  = "statevector"

selected_mask_p2 = solve_qaoa_clustered(
    scores_list=linear_scores_p2, label_prefix="y",
    qaoa_config=config_p2, n_cl=n_clusters)
n_selected_p2 = selected_mask_p2.sum()
print(f"  P2 全体選択拠点数: {n_selected_p2} / {n_nodes}")

# 選択結果 → 実数インセンティブ配列に変換
best_alloc_p2 = np.zeros(n_nodes)
scores_p2_arr = np.array(risk_scores_p2, dtype=float)

if n_selected_p2 > 0:
    sel_scores_p2 = scores_p2_arr * selected_mask_p2
    sel_total_p2  = sel_scores_p2.sum()
    if sel_total_p2 > 0:
        best_alloc_p2 += (sel_scores_p2 / sel_total_p2) * (BUDGET_P2 * SELECTED_RATIO)

non_mask_p2 = 1 - selected_mask_p2
n_non_p2    = non_mask_p2.sum()
if n_non_p2 > 0:
    best_alloc_p2 += non_mask_p2 * (BUDGET_P2 * remaining_ratio / n_non_p2)
else:
    best_alloc_p2 = (scores_p2_arr / scores_p2_arr.sum()) * BUDGET_P2

def unified_score_p2(incentives, df_ref, base_dist, weights):
    n     = len(incentives)
    score = 0.0
    for i in range(n):
        eff    = math.log1p(incentives[i])
        score += weights["impact"]  * eff * df_ref["risk_score"].iloc[i]
        score += weights["econ"]    * eff * (1000 / base_dist)
    if n > 1:
        score -= weights["fairness"] * (max(incentives) - min(incentives))
    return score

weights_p2     = {"impact": W_IMPACT, "econ": W_ECON, "fairness": W_FAIRNESS}
final_score_p2 = unified_score_p2(best_alloc_p2.tolist(), df, base_dist_p2, weights_p2)
print(f"  統合スコア (P2): {final_score_p2:.4f}")

qaoa_p2_end  = datetime.now()
qaoa_p2_time = (qaoa_p2_end - qaoa_p2_start).total_seconds()
print(f"  QAOA P2 実行時間: {qaoa_p2_time:.2f} 秒")
print(f"\n【⑥  QAOA によるリスク連動完了-実行Time】 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")


# ============================================================
# 全可視化（完全版）
# ============================================================
print(f"\n【全プロセス完了開始-実行Time】 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

results_df               = df.copy()
results_df["incentive_p1"] = best_alloc_p1
results_df["incentive_p2"] = best_alloc_p2
display(results_df[["source_name", "risk_score_static", "risk_score",
                     "incentive_p1", "incentive_p2"]])

heatmap_data = results_df[['source_name', 'incentive_p2', 'risk_score']]

# PHASE 2 インセンティブ棒グラフ
fig_p2 = go.Figure()
fig_p2.add_trace(go.Bar(
    x=results_df["source_name"],
    y=results_df["incentive_p2"],
    marker=dict(color=results_df["risk_score"], colorscale="Reds", showscale=True),
    text=results_df["incentive_p2"].round(0).astype(int).astype(str) + "円",
    textposition="auto",
))
fig_p2.update_layout(
    title="【PHASE 2】量子強化 動的リスク連動型インセンティブ配分 (QAOA クラスタ分割版)",
    yaxis_title="配分額 (円)", xaxis_title="拠点名",
    height=550, xaxis_tickangle=-45,
)
fig_p2.show()

# PHASE 1 vs PHASE 2 比較グラフ
fig_compare = go.Figure()
fig_compare.add_trace(go.Bar(
    name="PHASE 1（QAOA 静的・クラスタ分割）",
    x=farmers, y=best_alloc_p1, marker_color="mediumseagreen"))
fig_compare.add_trace(go.Bar(
    name="PHASE 2（QAOA＋量子リスク＋衛星・クラスタ分割）",
    x=results_df["source_name"], y=best_alloc_p2, marker_color="tomato"))
fig_compare.update_layout(
    barmode="group",
    title="PHASE 1 vs PHASE 2 比較（QAOA クラスタ分割版）",
    yaxis_title="配分額（円）")
fig_compare.show()

# リスクスコアとインセンティブの相関散布図
fig_scatter = px.scatter(
    heatmap_data,
    x='risk_score', y='incentive_p2', text='source_name',
    size='incentive_p2', color='risk_score',
    hover_name='source_name',
    hover_data={'incentive_p2': ':.2f', 'risk_score': True},
)
fig_scatter.update_traces(textposition='top center')
fig_scatter.update_layout(
    title='リスクスコアとインセンティブ配分の相関関係（QAOA クラスタ分割版）',
    xaxis_title='リスクスコア', yaxis_title='インセンティブ配分額 (円)', height=550)
fig_scatter.show()

# インセンティブ配分ヒートマップ
fig_heatmap = go.Figure(data=go.Heatmap(
    z=[heatmap_data['incentive_p2'].tolist()],
    x=heatmap_data['source_name'],
    y=['Incentive Value'],
    colorscale='Viridis',
    colorbar=dict(title='配分額 (円)'),
    text=[[f"リスクスコア: {r}<br>配分額: {i:.2f}円"
           for r, i in zip(heatmap_data['risk_score'], heatmap_data['incentive_p2'])]],
    texttemplate="%{text}", hoverinfo="text",
))
fig_heatmap.update_layout(
    title='【PHASE 2】インセンティブ配分ヒートマップ（QAOA クラスタ分割版）',
    xaxis_title='拠点名', yaxis_title='',
    yaxis=dict(showticklabels=False),
    height=400, margin=dict(l=50, r=50, b=100, t=80))
fig_heatmap.show()


# ============================================================
# 最終サマリ
# ============================================================
print("\n" + "=" * 70)
print("  最終サマリ")
print("=" * 70)
_v0_dist = route_v0['累積距離'].max() if not route_v0.empty else 0
_v1_dist = route_v1['累積距離'].max() if not route_v1.empty else 0
print(f"  対象拠点数            : {len(df)}")
print(f"  VRP 総距離(P1)        : {(_v0_dist + _v1_dist):.0f} m (2台)")
print(f"  VRP 総距離(P2)        : {base_dist_p2} m")
print(f"  予算総額              : ¥{int(BUDGET_P2):,}")
print(f"  P1 QAOA 最適スコア    : {max_score_p1:.2f}")
print(f"  P2 QAOA 統合スコア    : {final_score_p2:.4f}")
print(f"  P1 QAOA 選択拠点数    : {n_selected_p1} / {n_nodes}")
print(f"  P2 QAOA 選択拠点数    : {n_selected_p2} / {n_nodes}")
print(f"  QAOAサブ問題サイズ    : N_sub = {N_sub}  ({n_clusters}分割)")
print(f"  状態空間削減効果      : 2^{n_nodes}={2**n_nodes:,} "
      f"→ {n_clusters}×2^{N_sub}={n_clusters * 2**N_sub:,}")
print(f"  量子鍵ID              : {quantum_qkd_key()}")
print("=" * 70)

# ============================================================
# 最終実験ログ（CSV用）
# ============================================================
total_time = (datetime.now() - overall_start_time).total_seconds()

print("\n" + "=" * 80)
print("【実験ログ（CSV用）】")
print(f"n_nodes,{n_nodes},"
      f"N_sub,{N_sub},"
      f"QAOA_P1_sec,{qaoa_p1_time:.2f},"
      f"QAOA_P2_sec,{qaoa_p2_time:.2f},"
      f"VRP_P1_sec,{vrp_time:.2f},"
      f"VRP_P2_sec,{vrp_p2_time:.2f},"
      f"Total_sec,{total_time:.2f},"
      f"method,QAOA+ClusterSplit,"
      f"clusters,{n_clusters}")

print(f"n_nodes={n_nodes} | N_sub={N_sub} | "
      f"QAOA_P1: {qaoa_p1_time:.1f}s | "
      f"QAOA_P2: {qaoa_p2_time:.1f}s | "
      f"VRP_P1: {vrp_time:.1f}s | "
      f"VRP_P2: {vrp_p2_time:.1f}s | "
      f"合計: {total_time:.1f}s | "
      f"Clusters: {n_clusters}")
print("=" * 80)

print(f"\n【全プロセス完了-実行Time】 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print("✅ 全プロセス完了！（QAOA クラスタ分割 + 量子アニーリング 統合版）")